name: Reproducible bug report
description: Create a reproducible bug report. Not for support requests.
labels: [ bug ]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Pre-requisites
      options:
        - label: I have double-checked my configuration
          required: true
        - label: I can confirm the issues exists when I tested with `:latest`
          required: true
        - label: I'd like to contribute the fix myself
  - type: textarea
    id: description
    attributes:
      label: What happened/what did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. master or latest
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs from the runner-talk
      render: text
    validations:
      required: true